server:
    port: 8081

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5432/fitness-user-db
        username: postgres
        password: Hana@123
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/